name: plasmabio-M1MEG_UE5_R
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - pip
  - gfortran_linux-64
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # R environment
  - r-irkernel
  - r-base>=4.1.0
  - r-tidyverse
  - r-rcpp
  - r-dt
  - r-markdown
  - r-tidyverse
  - r-repr
  - r-writexl
  - r-readxl
  - r-rcolorbrewer
  - r-gtools
  - r-gplots
  - r-statmod
  - r-poppr
  - r-moimix
  - r-adgenet
  - r-rehh
  - r-ggpmisc
  - r-ggprisms
  - r-ggtext
  - r-bioconductor-gdsfmt
  - r-bioconductor-snprelate
  - r-reconproGS 
  - r-bioconductor-seqarray
